/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MainTable: typeof import('./src/components/mainTable.vue')['default']
    NestedTable: typeof import('./src/components/nestedTable.vue')['default']
    ParentTable: typeof import('./src/components/parentTable.vue')['default']
    'ParentTabşe': typeof import('./src/components/parentTabşe.vue')['default']
  }
}
